//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcija.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiviraj.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivan.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj državljanstvo.
        /// </summary>
        public static string AddCitizenship {
            get {
                return ResourceManager.GetString("AddCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj grad.
        /// </summary>
        public static string AddCity {
            get {
                return ResourceManager.GetString("AddCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj kontakt.
        /// </summary>
        public static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj tip kontakta.
        /// </summary>
        public static string AddContactType {
            get {
                return ResourceManager.GetString("AddContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj državu.
        /// </summary>
        public static string AddCountry {
            get {
                return ResourceManager.GetString("AddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nacionalnost.
        /// </summary>
        public static string AddNationality {
            get {
                return ResourceManager.GetString("AddNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj ulogu.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj korisnika.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipovi obavijesti.
        /// </summary>
        public static string AnnouncementTypes {
            get {
                return ResourceManager.GetString("AnnouncementTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacijske postavke.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u.
        /// </summary>
        public static string AtTime {
            get {
                return ResourceManager.GetString("AtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosanski.
        /// </summary>
        public static string Bosnian {
            get {
                return ResourceManager.GetString("Bosnian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakpoint.
        /// </summary>
        public static string Breakpoint {
            get {
                return ResourceManager.GetString("Breakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni sliku.
        /// </summary>
        public static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni lozinku.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni sliku.
        /// </summary>
        public static string ChangePhoto {
            get {
                return ResourceManager.GetString("ChangePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite državu.
        /// </summary>
        public static string ChooseCountry {
            get {
                return ResourceManager.GetString("ChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradovi.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Državljanstvo.
        /// </summary>
        public static string Citizenship {
            get {
                return ResourceManager.GetString("Citizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Državljanstva.
        /// </summary>
        public static string Citizenships {
            get {
                return ResourceManager.GetString("Citizenships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdite novu lozinku.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi lozinku.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktni podaci.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakti.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta kontakta.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipovi kontakata.
        /// </summary>
        public static string ContactTypes {
            get {
                return ResourceManager.GetString("ContactTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Države.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaka države.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna lozinka.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazujem 0 do 0 od 0 zapisa.
        /// </summary>
        public static string DataTableInfoEmpty {
            get {
                return ResourceManager.GetString("DataTableInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtrirano iz _MAX_ zapisa).
        /// </summary>
        public static string DataTableInfoFiltered {
            get {
                return ResourceManager.GetString("DataTableInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži _MENU_ zapisa.
        /// </summary>
        public static string DataTableLengthMenu {
            get {
                return ResourceManager.GetString("DataTableLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrađujem....
        /// </summary>
        public static string DataTableProcessing {
            get {
                return ResourceManager.GetString("DataTableProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazujem od _START_ do _END_ od _TOTAL_ zapisa.
        /// </summary>
        public static string DataTableShowingStartToEnd {
            get {
                return ResourceManager.GetString("DataTableShowingStartToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy u HH:mm.
        /// </summary>
        public static string DateFormatLong {
            get {
                return ResourceManager.GetString("DateFormatLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktiviraj.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni državljanstvo.
        /// </summary>
        public static string EditCitizenship {
            get {
                return ResourceManager.GetString("EditCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni grad.
        /// </summary>
        public static string EditCity {
            get {
                return ResourceManager.GetString("EditCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni tip kontakta.
        /// </summary>
        public static string EditContactTypes {
            get {
                return ResourceManager.GetString("EditContactTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni državu.
        /// </summary>
        public static string EditCountry {
            get {
                return ResourceManager.GetString("EditCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni nacionalnost.
        /// </summary>
        public static string EditNationality {
            get {
                return ResourceManager.GetString("EditNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni ulogu.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poštovani {0},
        ///&lt;br /&gt; &lt;br /&gt;
        ///primili ste ovaj mail jer je {1} kreiran korisnički račun na {2}. Da biste aktivirali korisnički račun, unesite u polje sljedeći aktivacijski kod:
        ///&lt;h2 style=&quot;color:#19a6d0&quot;&gt;{3}&lt;/h2&gt;
        ///&lt;br/&gt;&lt;br/&gt;Ukoliko ne vidite polje za unos aktivacijskog koda pokušajte se prijaviti putem aplikacije. U trenuktu prijave pojavit će vam se polje za unos aktivacijskog koda.&lt;br/&gt;&lt;br/&gt;
        ///S poštovanjem,&lt;br/&gt;
        ///{2} Administracija&lt;br/&gt;&lt;br/&gt;&lt;hr&gt;.
        /// </summary>
        public static string EmailMsgRegistration {
            get {
                return ResourceManager.GetString("EmailMsgRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtjev za registraciju.
        /// </summary>
        public static string EmailTitleRegistration {
            get {
                return ResourceManager.GetString("EmailTitleRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtjev za resetovanje lozinke.
        /// </summary>
        public static string EmailTitleRequestForPasswordRecovery {
            get {
                return ResourceManager.GetString("EmailTitleRequestForPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnički račun nije aktiviran..
        /// </summary>
        public static string ErrMsgAccountNeedsActivaiton {
            get {
                return ResourceManager.GetString("ErrMsgAccountNeedsActivaiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivacijski kod nije validan..
        /// </summary>
        public static string ErrMsgActivationCodeNotValid {
            get {
                return ResourceManager.GetString("ErrMsgActivationCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje &apos;Aktivan&apos; je obavezno..
        /// </summary>
        public static string ErrMsgActiveReq {
            get {
                return ResourceManager.GetString("ErrMsgActiveReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta dodatne informacije je obavezna..
        /// </summary>
        public static string ErrMsgAdditionalInformationTypeReq {
            get {
                return ResourceManager.GetString("ErrMsgAdditionalInformationTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja je obavezno..
        /// </summary>
        public static string ErrMsgBirthDateReq {
            get {
                return ResourceManager.GetString("ErrMsgBirthDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt &quot;{0}&quot; već se koristi od strane drugog korisnika..
        /// </summary>
        public static string ErrMsgContactInUse {
            get {
                return ResourceManager.GetString("ErrMsgContactInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakti ne mogu biti izmijenjeni..
        /// </summary>
        public static string ErrMsgContactsEdited {
            get {
                return ResourceManager.GetString("ErrMsgContactsEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država je obavezna..
        /// </summary>
        public static string ErrMsgCountry {
            get {
                return ResourceManager.GetString("ErrMsgCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina oznake države je 10 karaktera..
        /// </summary>
        public static string ErrMsgCountryCodeLen {
            get {
                return ResourceManager.GetString("ErrMsgCountryCodeLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum dodavanja je obavezan..
        /// </summary>
        public static string ErrMsgCreatedDateReq {
            get {
                return ResourceManager.GetString("ErrMsgCreatedDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna lozinka je obavezna..
        /// </summary>
        public static string ErrMsgCurrentPasswordReq {
            get {
                return ResourceManager.GetString("ErrMsgCurrentPasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum je obavezan..
        /// </summary>
        public static string ErrMsgDateReq {
            get {
                return ResourceManager.GetString("ErrMsgDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dan je obavezan..
        /// </summary>
        public static string ErrMsgDayReq {
            get {
                return ResourceManager.GetString("ErrMsgDayReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posljednji primarni kontakt nije moguće obrisati..
        /// </summary>
        public static string ErrMsgDeleteLastPrimary {
            get {
                return ResourceManager.GetString("ErrMsgDeleteLastPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje izleta je obavezno..
        /// </summary>
        public static string ErrMsgDurationInDaysReq {
            get {
                return ResourceManager.GetString("ErrMsgDurationInDaysReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je zauzet..
        /// </summary>
        public static string ErrMsgEmailAlreadyExists {
            get {
                return ResourceManager.GetString("ErrMsgEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina email adrese je 100 karaktera..
        /// </summary>
        public static string ErrMsgEmailLen100 {
            get {
                return ResourceManager.GetString("ErrMsgEmailLen100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa &quot;{0}&quot; nije validna..
        /// </summary>
        public static string ErrMsgEmailNotValid {
            get {
                return ResourceManager.GetString("ErrMsgEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je obavezan..
        /// </summary>
        public static string ErrMsgEmailReq {
            get {
                return ResourceManager.GetString("ErrMsgEmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina imena je 50 karaktera..
        /// </summary>
        public static string ErrMsgFirstNameLen50 {
            get {
                return ResourceManager.GetString("ErrMsgFirstNameLen50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno..
        /// </summary>
        public static string ErrMsgFirstNameReq {
            get {
                return ResourceManager.GetString("ErrMsgFirstNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške. Molim pokušajte kasnije. .
        /// </summary>
        public static string ErrMsgFrinedly {
            get {
                return ResourceManager.GetString("ErrMsgFrinedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina spola je 10 karaktera..
        /// </summary>
        public static string ErrMsgGenderLen10 {
            get {
                return ResourceManager.GetString("ErrMsgGenderLen10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spol je obavezan..
        /// </summary>
        public static string ErrMsgGenderReq {
            get {
                return ResourceManager.GetString("ErrMsgGenderReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocjena je obavezna..
        /// </summary>
        public static string ErrMsgGradeReq {
            get {
                return ResourceManager.GetString("ErrMsgGradeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupa je obavezana..
        /// </summary>
        public static string ErrMsgGroupReq {
            get {
                return ResourceManager.GetString("ErrMsgGroupReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika ne može biti izmijenjena..
        /// </summary>
        public static string ErrMsgImageEdit {
            get {
                return ResourceManager.GetString("ErrMsgImageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika mora biti u .PNG ili .JPG formatu..
        /// </summary>
        public static string ErrMsgImageFormat {
            get {
                return ResourceManager.GetString("ErrMsgImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimenzije slike ne mogu biti manje od {0}x{1} piksela..
        /// </summary>
        public static string ErrMsgImageResolution {
            get {
                return ResourceManager.GetString("ErrMsgImageResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veličina slike ne može biti veća od {0} MB..
        /// </summary>
        public static string ErrMsgImageSize {
            get {
                return ResourceManager.GetString("ErrMsgImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan autentifikacijski token..
        /// </summary>
        public static string ErrMsgInvalidAuthToken {
            get {
                return ResourceManager.GetString("ErrMsgInvalidAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token za resetovanje je istekao ili nije validan..
        /// </summary>
        public static string ErrMsgInvalidOrExpiredResetPasswordToken {
            get {
                return ResourceManager.GetString("ErrMsgInvalidOrExpiredResetPasswordToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina prezimena je 50 karaktera..
        /// </summary>
        public static string ErrMsgLastNameLen50 {
            get {
                return ResourceManager.GetString("ErrMsgLastNameLen50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno..
        /// </summary>
        public static string ErrMsgLastNameReq {
            get {
                return ResourceManager.GetString("ErrMsgLastNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Član je obavezan..
        /// </summary>
        public static string ErrMsgMemberReq {
            get {
                return ResourceManager.GetString("ErrMsgMemberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do validacijskih grešaka..
        /// </summary>
        public static string ErrMsgModelstateNotValid {
            get {
                return ResourceManager.GetString("ErrMsgModelstateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoteka mora biti slika..
        /// </summary>
        public static string ErrMsgMustBeImage {
            get {
                return ResourceManager.GetString("ErrMsgMustBeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina naziva je 100 karaktera..
        /// </summary>
        public static string ErrMsgNameLen100 {
            get {
                return ResourceManager.GetString("ErrMsgNameLen100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv je obavezan..
        /// </summary>
        public static string ErrMsgNameReq {
            get {
                return ResourceManager.GetString("ErrMsgNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka je obavezna..
        /// </summary>
        public static string ErrMsgNewPasswordReq {
            get {
                return ResourceManager.GetString("ErrMsgNewPasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je odabrati barem jednu funkcionalnost..
        /// </summary>
        public static string ErrMsgNoFucntionality {
            get {
                return ResourceManager.GetString("ErrMsgNoFucntionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj putnika je obavezan..
        /// </summary>
        public static string ErrMsgNumberOfPassengersReq {
            get {
                return ResourceManager.GetString("ErrMsgNumberOfPassengersReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj mjesta je obavezno..
        /// </summary>
        public static string ErrMsgNumberOfPlacesReq {
            get {
                return ResourceManager.GetString("ErrMsgNumberOfPlacesReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stranica kojoj pokušavate pristupiti nije pronađena..
        /// </summary>
        public static string ErrMsgPageNotFound {
            get {
                return ResourceManager.GetString("ErrMsgPageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina imena roditelja je 50 karaktera..
        /// </summary>
        public static string ErrMsgParentNameLen50 {
            get {
                return ResourceManager.GetString("ErrMsgParentNameLen50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime roditelja je obavezno..
        /// </summary>
        public static string ErrMsgParentNameReq {
            get {
                return ResourceManager.GetString("ErrMsgParentNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora sadržavati najmanje 6 karaktera (kombinacija slova i brojeva)..
        /// </summary>
        public static string ErrMsgPasswordComplex {
            get {
                return ResourceManager.GetString("ErrMsgPasswordComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora sadržavati najmanje 6 karaktera (kombinacija slova i brojeva)..
        /// </summary>
        public static string ErrMsgPasswordComplexity {
            get {
                return ResourceManager.GetString("ErrMsgPasswordComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda lozinke je obavezna..
        /// </summary>
        public static string ErrMsgPasswordConfirmReq {
            get {
                return ResourceManager.GetString("ErrMsgPasswordConfirmReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina hasha lozinke je 100 karaktera..
        /// </summary>
        public static string ErrMsgPasswordHashLen100 {
            get {
                return ResourceManager.GetString("ErrMsgPasswordHashLen100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka koju ste unijeli nije validna..
        /// </summary>
        public static string ErrMsgPasswordIncorrect {
            get {
                return ResourceManager.GetString("ErrMsgPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda lozinke nije validna..
        /// </summary>
        public static string ErrMsgPasswordNoMatch {
            get {
                return ResourceManager.GetString("ErrMsgPasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezna..
        /// </summary>
        public static string ErrMsgPasswordRequired {
            get {
                return ResourceManager.GetString("ErrMsgPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina salta lozinke je 100 karaktera..
        /// </summary>
        public static string ErrMsgPasswordSaltLen100 {
            get {
                return ResourceManager.GetString("ErrMsgPasswordSaltLen100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke se ne poklapaju..
        /// </summary>
        public static string ErrMsgPasswordsNotMatch {
            get {
                return ResourceManager.GetString("ErrMsgPasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format slike nije dozvoljen..
        /// </summary>
        public static string ErrMsgPhotoFormat {
            get {
                return ResourceManager.GetString("ErrMsgPhotoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalna rezolucija slike je 150x225..
        /// </summary>
        public static string ErrMsgPhotoResolution {
            get {
                return ResourceManager.GetString("ErrMsgPhotoResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika je prevelika. Maksimalna veličina slike je 500 KB..
        /// </summary>
        public static string ErrMsgPhotoSize {
            get {
                return ResourceManager.GetString("ErrMsgPhotoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena je obavezna.
        /// </summary>
        public static string ErrMsgPriceReq {
            get {
                return ResourceManager.GetString("ErrMsgPriceReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primarna email adresa je obavezana..
        /// </summary>
        public static string ErrMsgPrimaryEmailReq {
            get {
                return ResourceManager.GetString("ErrMsgPrimaryEmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis ne može biti dodan. .
        /// </summary>
        public static string ErrMsgRecordAdded {
            get {
                return ResourceManager.GetString("ErrMsgRecordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis ne može biti obrisan jer je povezan sa drugim podacima..
        /// </summary>
        public static string ErrMsgRecordDeleted {
            get {
                return ResourceManager.GetString("ErrMsgRecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis ne može biti izmijenjen. .
        /// </summary>
        public static string ErrMsgRecordEdited {
            get {
                return ResourceManager.GetString("ErrMsgRecordEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina recenzije je 500 karaktera..
        /// </summary>
        public static string ErrMsgReviewLen500 {
            get {
                return ResourceManager.GetString("ErrMsgReviewLen500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recenzija je obavezna..
        /// </summary>
        public static string ErrMsgReviewReq {
            get {
                return ResourceManager.GetString("ErrMsgReviewReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga je obavezan..
        /// </summary>
        public static string ErrMsgRoleReq {
            get {
                return ResourceManager.GetString("ErrMsgRoleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka mora biti različita od trenutne..
        /// </summary>
        public static string ErrMsgSameOldNewPassword {
            get {
                return ResourceManager.GetString("ErrMsgSameOldNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina vremena je 10 karaktera..
        /// </summary>
        public static string ErrMsgTimeLen10 {
            get {
                return ResourceManager.GetString("ErrMsgTimeLen10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina naslova je 200 karaktera..
        /// </summary>
        public static string ErrMsgTitleLen200 {
            get {
                return ResourceManager.GetString("ErrMsgTitleLen200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov je obavezan..
        /// </summary>
        public static string ErrMsgTitleReq {
            get {
                return ResourceManager.GetString("ErrMsgTitleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin izleta je obavezan..
        /// </summary>
        public static string ErrMsgTourDateReq {
            get {
                return ResourceManager.GetString("ErrMsgTourDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izlet je obavezan..
        /// </summary>
        public static string ErrMsgTourReq {
            get {
                return ResourceManager.GetString("ErrMsgTourReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervacija je obavezna..
        /// </summary>
        public static string ErrMsgTourReservationReq {
            get {
                return ResourceManager.GetString("ErrMsgTourReservationReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno nije moguće izvršiti registraciju..
        /// </summary>
        public static string ErrMsgUnableToRegister {
            get {
                return ResourceManager.GetString("ErrMsgUnableToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno nije moguće poslati mail..
        /// </summary>
        public static string ErrMsgUnableToSendMail {
            get {
                return ResourceManager.GetString("ErrMsgUnableToSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neovlašten pristup.
        /// </summary>
        public static string ErrMsgUnauthorizedAccess {
            get {
                return ResourceManager.GetString("ErrMsgUnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovaj korisnički račun je aktiviran..
        /// </summary>
        public static string ErrMsgUserAccountAlreadyActived {
            get {
                return ResourceManager.GetString("ErrMsgUserAccountAlreadyActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnički račun je deaktiviran ili nije izvšena aktivacija..
        /// </summary>
        public static string ErrMsgUserAccountNotActive {
            get {
                return ResourceManager.GetString("ErrMsgUserAccountNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnički račun nije pronađen..
        /// </summary>
        public static string ErrMsgUserAccountNotFound {
            get {
                return ResourceManager.GetString("ErrMsgUserAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto..
        /// </summary>
        public static string ErrMsgUsernameAlreadyExists {
            get {
                return ResourceManager.GetString("ErrMsgUsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste unijeli validno korisničko ime ili lozinku..
        /// </summary>
        public static string ErrMsgUsernameAndPasswordReq {
            get {
                return ResourceManager.GetString("ErrMsgUsernameAndPasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina korisničkog imena je 100 karaktera..
        /// </summary>
        public static string ErrMsgUserNameLen100 {
            get {
                return ResourceManager.GetString("ErrMsgUserNameLen100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno..
        /// </summary>
        public static string ErrMsgUserNameReq {
            get {
                return ResourceManager.GetString("ErrMsgUserNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik je obavezan..
        /// </summary>
        public static string ErrMsgUserReq {
            get {
                return ResourceManager.GetString("ErrMsgUserReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina vrijednosti je 100 karaktera..
        /// </summary>
        public static string ErrMsgValueLen100 {
            get {
                return ResourceManager.GetString("ErrMsgValueLen100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijednost je obavezna..
        /// </summary>
        public static string ErrMsgValueReq {
            get {
                return ResourceManager.GetString("ErrMsgValueReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prva stranica.
        /// </summary>
        public static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaboravljena lozinka?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite Vašu e-mail adresu i pritisnite dugme &quot;Pošalji&quot;. Na mail ćete dobiti link za unos nove lozinke..
        /// </summary>
        public static string ForgotPasswordMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcionalnosti.
        /// </summary>
        public static string Functionalities {
            get {
                return ResourceManager.GetString("Functionalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcionalnost.
        /// </summary>
        public static string Functionality {
            get {
                return ResourceManager.GetString("Functionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spol.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ženksi.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muški.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opšte postavke.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Članstva u grupama.
        /// </summary>
        public static string GroupMemberships {
            get {
                return ResourceManager.GetString("GroupMemberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv grupe.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija u grupi.
        /// </summary>
        public static string GroupPosition {
            get {
                return ResourceManager.GetString("GroupPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Članstva u grupama.
        /// </summary>
        public static string GroupsInformation {
            get {
                return ResourceManager.GetString("GroupsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešno korisničko ime i/ili lozinka..
        /// </summary>
        public static string IncorrectLoginCredentials {
            get {
                return ResourceManager.GetString("IncorrectLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poštovana {0},
        ///&lt;br /&gt; &lt;br /&gt;
        ///primili ste ovaj mail jer je {1} poslan zahtjev za resetovanje lozinke na {2} za Vaš korisnički račun. Da biste nastavili proces resetovanja lozinke, unesite u polje sljedeći verifikacijski kod:
        ///&lt;h2 style=&quot;color:#19a6d0&quot;&gt;{3}&lt;/h2&gt;
        ///&lt;br/&gt;&lt;br/&gt;Verifikacijski kod za resetovanje lozinke ima ograničeno vrijeme trajanja od 20 minuta kada prestaje biti važeći i bit će potrebno da ponovo pošaljete zahtjev.&lt;br/&gt;&lt;br/&gt;
        ///S poštovanjem,&lt;br/&gt;
        ///{2} Administracija&lt;br/&gt;&lt;br/&gt;&lt;hr&gt;
        ///&lt;span style=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InfoEmailMsgForgetPasswordFemale {
            get {
                return ResourceManager.GetString("InfoEmailMsgForgetPasswordFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poštovani {0},
        ///&lt;br /&gt; &lt;br /&gt;
        ///primili ste ovaj mail jer je {1} poslan zahtjev za resetovanje lozinke na {2} za Vaš korisnički račun. Da biste nastavili proces resetovanja lozinke, unesite u polje sljedeći verifikacijski kod:
        ///&lt;h2 style=&quot;color:#19a6d0&quot;&gt;{3}&lt;/h2&gt;
        ///&lt;br/&gt;&lt;br/&gt;Verifikacijski kod za resetovanje lozinke ima ograničeno vrijeme trajanja od 20 minuta kada prestaje biti važeći i bit će potrebno da ponovo pošaljete zahtjev.&lt;br/&gt;&lt;br/&gt;
        ///S poštovanjem,&lt;br/&gt;
        ///{2} Administracija&lt;br/&gt;&lt;br/&gt;&lt;hr&gt;
        ///&lt;span style=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InfoEmailMsgForgetPasswordMale {
            get {
                return ResourceManager.GetString("InfoEmailMsgForgetPasswordMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posljednja stranica.
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime i lozinku.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupe članova.
        /// </summary>
        public static string MemberGroups {
            get {
                return ResourceManager.GetString("MemberGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicije članova.
        /// </summary>
        public static string MemberPositions {
            get {
                return ResourceManager.GetString("MemberPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum učlanjivanja.
        /// </summary>
        public static string MembershipDate {
            get {
                return ResourceManager.GetString("MembershipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership organizer.
        /// </summary>
        public static string MembershipOrganizer {
            get {
                return ResourceManager.GetString("MembershipOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip članstva.
        /// </summary>
        public static string MembershipType {
            get {
                return ResourceManager.GetString("MembershipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipovi članstava.
        /// </summary>
        public static string MembershipTypes {
            get {
                return ResourceManager.GetString("MembershipTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titule članova.
        /// </summary>
        public static string MemberTitles {
            get {
                return ResourceManager.GetString("MemberTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivacijski link je poslan na Vašu e-mail adresu..
        /// </summary>
        public static string MsgActivationLinkSend {
            get {
                return ResourceManager.GetString("MsgActivationLinkSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je usješno resetovana..
        /// </summary>
        public static string MsgPasswordReseted {
            get {
                return ResourceManager.GetString("MsgPasswordReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moji podaci.
        /// </summary>
        public static string MyInformation {
            get {
                return ResourceManager.GetString("MyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalnosti.
        /// </summary>
        public static string Nationalities {
            get {
                return ResourceManager.GetString("Nationalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalnost.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sljedeće.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema rezultata.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema rezultata koji odgovaraju vašoj pretrazi..
        /// </summary>
        public static string NoResultsMatch {
            get {
                return ResourceManager.GetString("NoResultsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj mjesta.
        /// </summary>
        public static string NumberOfPlaces {
            get {
                return ResourceManager.GetString("NumberOfPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime roditelja.
        /// </summary>
        public static string ParentName {
            get {
                return ResourceManager.GetString("ParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni lozinku.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobni podaci.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mjesto.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prethodno.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primarni.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEMAM IDEJE.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018.
        /// </summary>
        public static string ProjectStartYear {
            get {
                return ResourceManager.GetString("ProjectStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni?.
        /// </summary>
        public static string QConfirm {
            get {
                return ResourceManager.GetString("QConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisa.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preusmjeravam na početnu....
        /// </summary>
        public static string RedirectingToTheHomepage {
            get {
                return ResourceManager.GetString("RedirectingToTheHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regionalne postavke.
        /// </summary>
        public static string RegionalSettings {
            get {
                return ResourceManager.GetString("RegionalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamti me.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezna izmjena lozinke.
        /// </summary>
        public static string RequiredPasswordChange {
            get {
                return ResourceManager.GetString("RequiredPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetuj lozinku.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji uloga.
        /// </summary>
        public static string RoleDetails {
            get {
                return ResourceManager.GetString("RoleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloge.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga korisnika.
        /// </summary>
        public static string SearchUsers {
            get {
                return ResourceManager.GetString("SearchUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabran.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi sliku.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi sliku.
        /// </summary>
        public static string SelectPhoto {
            get {
                return ResourceManager.GetString("SelectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pošalji.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ž.
        /// </summary>
        public static string ShortGenderFemale {
            get {
                return ResourceManager.GetString("ShortGenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string ShortGenderMale {
            get {
                return ResourceManager.GetString("ShortGenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazujem od {0} do {1} od {2} zapisa.
        /// </summary>
        public static string ShowingStartToEnd {
            get {
                return ResourceManager.GetString("ShowingStartToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakti su uspješno izmijenjeni..
        /// </summary>
        public static string SuccessMsgContactsEdited {
            get {
                return ResourceManager.GetString("SuccessMsgContactsEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status je uspješno izmijenjen..
        /// </summary>
        public static string SuccessMsgEditStatus {
            get {
                return ResourceManager.GetString("SuccessMsgEditStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika je uspješno izmijenjena..
        /// </summary>
        public static string SuccessMsgImageEdit {
            get {
                return ResourceManager.GetString("SuccessMsgImageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis je uspješno dodan..
        /// </summary>
        public static string SuccessMsgRecordAdded {
            get {
                return ResourceManager.GetString("SuccessMsgRecordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis je uspješno obrisan..
        /// </summary>
        public static string SuccessMsgRecordDeleted {
            get {
                return ResourceManager.GetString("SuccessMsgRecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis je uspješno izmijenjen..
        /// </summary>
        public static string SuccessMsgRecordEdited {
            get {
                return ResourceManager.GetString("SuccessMsgRecordEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke sistema.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titula.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje izleta (dan).
        /// </summary>
        public static string TourDuration {
            get {
                return ResourceManager.GetString("TourDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnički račun.
        /// </summary>
        public static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnički račun je uspješno aktiviran..
        /// </summary>
        public static string UserAccountSuccessfullyActivated {
            get {
                return ResourceManager.GetString("UserAccountSuccessfullyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o korisniku.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnici.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijednost.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
